name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Github Pages Auto Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Checkout Next Theme
        uses: actions/checkout@v2
        with:
          repository: theme-next/hexo-theme-next
          ref: master
          path: themes/next
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
      - name: Build
        run: |
          cp _config.next.yml themes/next/_config.yml
          sudo apt-get install pandoc
          npm install hexo-cli -g
          npm install
          hexo clean
          hexo generate
      
      - name: Deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # mkdir -p ~/.ssh/
          # echo "$ACCESS_TOKEN" | tr -d '\r' > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          # ssh-keyscan github.com >> ~/.ssh/known_hosts
          # git config --global user.name "PeriodicLaw"
          # git config --global user.email "periodiclaw0120@gmail.com"
          hexo deploy